### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wermarter** [wermarter/diut#49]
refactor bootstrap + config + exception filter
database daily backup
remove NX -> pnpm workspace
helm
study rxjs
golang usb port client

**Comment by wermarter** [comment]
user: (can login)
- branch member
- branch manager
- admin

external client: (cannot login)
- patient: JWT with authorization detail
- external system:
	- machine result reader
	- patient management system

**Comment by wermarter** [comment]
Clean architecture:
- [ ] TestCategory
- [ ] Test
- [ ] TestElement
- [ ] Patient
- [ ] Sample

**Comment by wermarter** [comment]
UI notes:
- [ ] patient info autocomplete ui change -> type name and birth / id --> autofill matching info
- [ ] URL search params persist page size and page number (optionally scroll position)
- [ ] batch input result and printing

**Comment by wermarter** [comment]
Later:
- [ ] contour envoy external authorization with @diut/hcdc-auth-service: asymmetric jwt
- [ ] socketio: youtube watch later + https://dev.to/hienngm/designing-a-highly-scalable-chat-application-for-handling-high-user-loads-in-nestjs-5big
